### PR TITLE
update: make test pass

### PR DESCRIPTION
**Pull request by videmsky**

### CODE REVIEW

**Review by ringods — APPROVED** [review]

**Comment by iwahbe** [comment]
@videmsky @ringods do you want to merge this PR?

**Comment by videmsky** [comment]
yes please!

**Review by ringods — APPROVED** [review]

**Comment by videmsky** [comment]
strange, the "Merge pull request" button is disabled for me. I've merged PRs with your approval before. Did roles change?

**Comment by ringods** [comment]
I suggest you create a PR to change this line from `maintain` to `admin`:

https://github.com/pulumiverse/infra/blob/main/03-members/videmsky.yaml#L2

**Pull request merged**
